######################################################################
# Automatically generated by qmake (2.01a) Tue May 31 20:46:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
